### ISSUE TITLE
error about mural_predict tools

### ISSUE THREAD

**Issue by bighawkin** [CaiLiLab/MuRaL#5]
when I try to run example data. 

singularity exec  mural_v1.1.0.sif  mural_predict --ref_genome data/seq.fa --test_data data/testing.bed.gz --model_path models/checkpoint_6/model --model_config_path models/checkpoint_6/model.fdiri_cal.pkl --pred_file testing.ckpt6.fdiri.tsv.gz --without_h5 --cpu_only > test3.out 2> test3.err

The end get two file. test3.out and test3.err.
test3.out:
/opt/conda/bin/mural_predict --ref_genome data/seq.fa --test_data data/testing.bed.gz --model_path models/checkpoint_6/model --model_config_path models/checkpoint_6/model.fdiri_cal.pkl --pred_file testing.ckpt6.fdiri.tsv.gz --without_h5 --cpu_only
ref_genome: data/seq.fa
test_data: data/testing.bed.gz
model_path: models/checkpoint_6/model
model_config_path: models/checkpoint_6/model.fdiri_cal.pkl
pred_file: testing.ckpt6.fdiri.tsv.gz
calibrator_path: 
bw_paths: None
n_h5_files: 1
without_h5: True
cpu_only: True
pred_batch_size: 16
kmer_corr: []
region_corr: []

test3.err is
Traceback (most recent call last):
  File "/opt/conda/bin/mural_predict", line 7, in <module>
    main()
  File "/home/ug0409/.local/lib/python3.8/site-packages/MuRaL/run_predict.py", line 214, in main
    local_radius = config['local_radius']
TypeError: 'FullDirichletCalibrator' object is not subscriptable

How can I deal with it. thank you

**Comment by cailigd** [comment]
@bighawkin

The config path in your command  was wrong. Please replace "models/checkpoint_6/model.fdiri_cal.pkl" by "models/checkpoint_6/model.config.pkl" .

**Comment by bighawkin** [comment]
Thank for your help, I have solved this problem. Thank you very much!
